@ECHO OFF
CHCP 65001
COLOR 0A
TITLE PSHODatabase Cloner
SETLOCAL ENABLEEXTENSIONS DISABLEDELAYEDEXPANSION
SET "SRC1=%~DP0"
SET "GIT=C:\Program Files\Git\bin"
SET "GITEXE=%GIT%\git.exe"
SET "GITLFS1=C:\Program Files\Git\cmd\git-lfs.exe"
SET "GITLFS2=C:\Program Files\Git LFS\git-lfs.exe"
SET "REPONAME=PSHODatabase"


:: CHECK IF GIT IS ALREADY IN THE PATH (OPTIONAL)
ECHO %PATH% | FIND /I "GIT\BIN" >NUL
IF %ERRORLEVEL%==0 (
    ECHO GIT IS ALREADY IN THE PATH.
    GOTO CONT
)

:: ADD GIT TO THE USER PATH
:: ADJUST THE PATH BELOW IF YOUR GIT INSTALLATION DIRECTORY IS DIFFERENT
SETX PATH "%PATH%;%GIT%"
ECHO GIT HAS BEEN ADDED TO YOUR ENVIRONMENT VARIABLES.

:CONT
IF NOT EXIST "%GIT%" ECHO GIT NOT FOUND @ END %GIT% & GOTO END

SETLOCAL ENABLEDELAYEDEXPANSION
SET "GITLFS="
IF NOT EXIST "%GITLFS1%" SET "GITLFS=!GITLFS!%GITLFS1%"
IF NOT "!GITLFS!" == "" (
    ECHO GIT LFS NOT FOUND @ !GITLFS!
    SET "GITLFSALT="
    IF NOT EXIST "%GITLFS2%" SET "GITLFSALT=!GITLFSALT!%GITLFS2%"
    IF NOT "!GITLFSALT!" == "" (
       ECHO GIT LFS NOT FOUND @ !GITLFS! OR !GITLFSALT!
    		GOTO END
    ) ELSE (
    	"%GITEXE%" lfs install
       GOTO MENU_MAIN
    )
) ELSE (
    "%GITEXE%" lfs install
    GOTO MENU_MAIN
)
ENDLOCAL

:MENU_MAIN
CD "%SRC1%"
ECHO.
ECHO.^|-------------^|
ECHO.^| GIT OPTIONS ^|
ECHO.^|-------------^|
ECHO.
ECHO 1. CLONE THE ENTIRE REPO
ECHO.
ECHO 2. UPDATE LOCAL REPO USING GIT PULL
ECHO.
ECHO 3. SUSPEND CMD
ECHO.
SET /P CHOICE=ENTER A NUMBER TO PERFORM AN ACTION: 
ECHO.
IF NOT '%CHOICE%'=='' SET CHOICE=%CHOICE:~0,1%
IF '%CHOICE%'=='1' GOTO MAIN_CHOICE_ONE
IF '%CHOICE%'=='2' GOTO MAIN_CHOICE_TWO
IF '%CHOICE%'=='3' GOTO MAIN_CHOICE_THREE

ECHO "%CHOICE%" IS NOT VALID, TRY AGAIN
ECHO.
GOTO MENU_MAIN

:MAIN_CHOICE_ONE
CALL :CLONE_ALL_FOLDERS
GOTO MAIN_OPTION_END

:MAIN_CHOICE_TWO
CALL :UPDATE_REPO
GOTO MAIN_OPTION_END

:MAIN_CHOICE_THREE
IF EXIST "%SRC1%%REPONAME%" CD "%SRC1%%REPONAME%"
CMD /K
GOTO MAIN_OPTION_END

:MAIN_OPTION_END
CMD /K
GOTO MENU_MAIN

:END
CMD /K


:CLONE_ALL_FOLDERS

ECHO INIT FULL CLONE OF REPO

IF EXIST "%SRC1%%REPONAME%\.git" (
	CD "%SRC1%%REPONAME%"
	"%GITEXE%" sparse-checkout disable
	"%GITEXE%" pull
 ) ELSE (
 	"%GITEXE%" clone https://github.com/pebxcvi/PSHODatabase.git
 )

GOTO MENU_MAIN

:UPDATE_REPO

ECHO INIT UPDATE OF REPO
ECHO.
ECHO.NOTE#4) IF ANY CHANGES ARE MADE TO YOUR LOCAL REPO, 
ECHO.SUSPEND CMD ( OPTION 4 ) THEN RUN "git stash" BEFORE YOU TRY TO PULL
ECHO. 

IF NOT EXIST "%SRC1%%REPONAME%" (
	ECHO NO GIT REPO FOUND @ "%SRC1%%REPONAME%"
) ELSE (
	CD "%SRC1%%REPONAME%"
	"%GITEXE%" pull
)

GOTO MENU_MAIN